
linux:
  hosts:
    alpine:
      ansible_host: 10.0.0.15
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
    centos:
      ansible_host: 10.0.0.12
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
    debian:
      ansible_host: 10.0.0.11
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
    suse:
      ansible_host: 10.0.0.14
      ansible_user: root
      required_ports:
      - 20
      - 21
      - 22
      ansible_password: Is1WaterWet?
    ubuntu:
      ansible_host: 10.0.0.10
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
    dash:
      ansible_host: 10.0.0.5
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
bsd:
  hosts:
    bsd:
      ansible_host: 10.0.0.13
      ansible_user: root
      ansible_password: Is1WaterWet?
      required_ports:
      - 20
      - 21
      - 22
windows:
  hosts:
    win2016:
      ansible_host: 10.0.0.16
      ansible_user: Administrator
      ansible_password: Is1WaterWet?
      ansible_connection: "winrm"
      ansible_winrm_scheme: "http"
      ansible_port: "5985"
      ansible_winrm_transport: "ntlm"
      domain_controller: true
      required_ports:
      - 22
      - 3389
    win2019:
      ansible_host: 10.0.0.17
      ansible_user: Administrator
      ansible_password: Is1WaterWet?
      ansible_connection: "winrm"
      ansible_winrm_scheme: "http"
      ansible_port: "5985"
      ansible_winrm_transport: "ntlm"
      domain_controller: true
      required_ports:
      - 22
      - 3389
manager:
  hosts:
    dash:
      ansible_host: 10.0.0.5
      ansible_user: root
      ansible_password: Is1WaterWet?
