windows:
  hosts:
    Windows2016:
      ansible_host: 10.0.0.16
      ansible_user: Administrator
      ansible_password: Is1WaterWet?
      ansible_connection: winrm
      ansible_winrm_scheme: http
      ansible_port: 5985
      ansible_winrm_transport: ntlm
      domain_controller: true
      in_domain: true
      required_ports:
      - 22
      - 53
    Windows2019:
      ansible_host: 10.0.0.17
      ansible_user: Administrator
      ansible_password: Is1WaterWet?
      ansible_connection: winrm
      ansible_winrm_scheme: http
      ansible_port: 5985
      ansible_winrm_transport: ntlm
      domain_controller: false
      in_domain: true
      required_ports:
      - 20
      - 21
      - 22
linux:
  hosts:
    Debian:
      ansible_host: 10.0.0.11
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: true
      required_ports:
      - 22
    Centos:
      ansible_host: 10.0.0.12
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: false
      required_ports:
      - 20
      - 21
      - 22
    Suse:
      ansible_host: 10.0.0.14
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: true
      required_ports:
      - 22
      - 53
    Ubuntu20:
      ansible_host: 10.0.0.5
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: false
      required_ports:
      - 22
      - 3306
    Ubuntu22:
      ansible_host: 10.0.0.10
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: true
      required_ports:
      - 22
      - 80
    Alpine:
      ansible_host: 10.0.0.15
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: true
      required_ports:
      - 22
bsd:
  hosts:
    FreeBased:
      ansible_host: 10.0.0.13
      ansible_user: root
      ansible_password: Is1WaterWet?
      ansible_connection: ssh
      in_domain: true
manager:
  hosts:
    Ubuntu20:
      ansible_host: 10.0.0.5
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: false
      required_ports:
      - 22
      - 3306 
