# UFSIT SCORINGENGINE (TM) CONFIG
# https://github.com/scoringengine/scoringengine
#
# remember that this file must be renamed and placed in bin/competition.yaml to work with the scoring engine
---
teams:
- name: WhiteTeam
  color: White
  users:
  - username: whiteteamuser
    password: testpass
- name: RedTeam
  color: Red
  users:
  - username: redteamuser
    password: testpass
- name: UFSitcom
  color: Blue
  users:
  - username: imblue
    password: imblue
  services:
  - name: QuasarLoud-ICMP
    check_name: ICMPCheck
    host: 10.119.119.5
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: QuasarLoud-SSH
    check_name: SSHCheck
    host: 10.119.119.5
    port: 22
    points: 150
    accounts:
    - username: lpalmer
      password: twinpeaks1
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: id;ls -l /home
    - matching_content: PID
      properties:
      - name: commands
        value: ps
  - name: QuasarLoud-HTTP
    check_name: HTTPCheck
    host: 10.119.119.5
    port: 80
    points: 100
    environments:
    - matching_content: This is the default welcome page used to test
      properties:
      - name: useragent
        value: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
      - name: vhost
        value: testbed_web
      - name: uri
        value: "/"
flags:
  - type: file
    platform: nix
    perm: user
    data:
        path: "/tmp/flag"
        content: "hi"
